#!/bin/zsh

export rmenu=$(echo "teste1\nteste2" | fzf \
    --border=rounded \
    --margin=5% \
    --color=dark \
    --height 100% \
    --reverse \
    --header=$(basename "Menu") \
    --info=hidden \
    --header-first \
    --prompt "$")
echo "$rmenu"

