#!/usr/bin/env bash

output=$("${@}" 2>&1)

if [[ ! $output =~ "panic" ]]; then
    echo "$output"
    exit 0
fi

local_path=$(pwd)

panic_line=$(echo "${output}" | grep "panic")

output=$(echo "$output" | \
    grep "$local_path" | \
    sed "s|$local_path/||g" | \
    sed "s| +.*||g" | \
    sed "s|\t||g")

IFS=: read -ra selected < <(echo "${output}" | fzf \
    --ansi \
    --delimiter : \
    --color=dark \
    --reverse \
    --header="${panic_line}" \
    --preview 'bat --color=always {1} --highlight-line {2}' \
    --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
)

[ -n "${selected[0]}" ] && \
    nvim "${selected[0]}" "+${selected[1]}" && \
    echo "${selected[0]}" "+${selected[1]}"


