#!/usr/bin/env bash

OUTPUT=$("${@}" 2>&1 | tee /dev/tty)

if [[ ! $OUTPUT =~ "panic" ]]; then
    exit $?
fi

LOCAL_PATH=$(pwd)

PANIC_LINE=$(echo "${OUTPUT}" | grep "panic")

OUTPUT=$(echo "$OUTPUT" | \
    grep "$LOCAL_PATH" | \
    sed "s|$LOCAL_PATH/||g" | \
    sed "s| +.*||g" | \
    sed "s|\t||g")

IFS=: read -ra SELECTED < <(echo "${OUTPUT}" | fzf \
    --ansi \
    --delimiter : \
    --color=dark \
    --reverse \
    --header="${PANIC_LINE}" \
    --preview 'bat --color=always {1} --highlight-line {2}' \
    --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
)

echo -e "\n\033[33;41m${PANIC_LINE}\033[0m"
echo -e "\n\033[35;40m${OUTPUT}\033[0m"

[ -n "${SELECTED[0]}" ] && \
    nvim "${SELECTED[0]}" "+${SELECTED[1]}" && \
    echo -e "\n\033[33;40m${SELECTED[0]} +${SELECTED[1]}\033[0m"

