#!/usr/bin/env bash

RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case --sort=modified --hidden --follow --glob '!{.git,node_modules}/*'"

while true; do
  # Recebe a consulta inicial, se houver
  INITIAL_QUERY="${*:-}"
  IFS=: read -ra selected < <(
    FZF_DEFAULT_COMMAND="$RG_PREFIX $(printf %q "$INITIAL_QUERY")" \
    fzf --ansi \
        --disabled --query "$INITIAL_QUERY" \
        --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
        --delimiter : \
        --preview 'bat --color=always {1} --highlight-line {2}' \
        --preview-window 'up,60%,border-bottom,+{2}+3/3,~3'
  )
  
  # Se algo foi selecionado, abre no editor; se não, sai do loop
  if [ -n "${selected[0]}" ]; then
    $EDITOR "${selected[0]}" "+${selected[1]}"
    echo "${selected[0]}" "+${selected[1]}"
  else
    break
  fi
done

